services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - .env.prod
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s